version: '3.8'
services:
  back:
    build: .
    container_name: name
    ports:
      - 9000:9000
    env_file: .env
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
  
  db:
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=best_app_test
    ports:
      - '5433:5432'
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
